### ISSUE TITLE
Add a linter config

### ISSUE THREAD

**Issue by drzax** [abcnews/aunty#1]
I have a slight preference for [eslint](https://atom.io/packages/linter-eslint) over [jshint](https://atom.io/packages/linter-jshint), but have both linters installed in Atom.

Would be good to have a default config file added such as `.eslintrc` or `.jshintrc`

**Comment by colingourlay** [comment]
Aunty itself uses `xo`, which is a wrapper around ESLint, so we may as well run that during project development, and use an optional `.eslintrc` for overrides. That way we can bake-in our global code style guide.

**Comment by drzax** [comment]
I'm in favour of that. Is there an xo config somewhere already or are we just using defaults?

**Comment by colingourlay** [comment]
Aunty now uses eslint & prettier itself, but we still haven't added any linting config to the projects it generates. I think we should create our own @abcnews namespaced eslint-config-* package, which projects (and aunty itself) can exend.

**Comment by drzax** [comment]
This sounds good.

**Comment by nathanhoad** [comment]
Closing this due to age and that its probably no longer relevant.
