### ISSUE TITLE
Optionally depend on private repos

### ISSUE THREAD

**Issue by drzax** [abcnews/aunty#118]
Sometimes I want to run builds of aunty on services like Vercel. That's no longer possible due to the dependency on private `@abcaustralia` libraries. Can we make those optional somehow?

**Comment by colingourlay** [comment]
I'd imagine we could move the @abcaustralia stuff to package.json's optionalDependencies, then try / catch require()-ing the ABC postcss config during the webpack config generation (skipping the @abcaustralia style-loading config in that case).

Beyond that, we just need devs to be aware that they can't use @abcaustralia component libraries in anything they want to push to a service like Vercel that does its own builds.
