### ISSUE TITLE
Proposal: drop Vue support in generators

### ISSUE THREAD

**Issue by drzax** [abcnews/aunty#127]
We don't think Vue is used (or has significant advantages over other supported options) and could be safely dropped from the template generation options in `aunty`. 

Please object if you intend to use Vue in the future.

**Comment by phocks** [comment]
I think it's probably safe to drop it. I added it originally just to see if I could get it working pretty much. I think I made 1 project in Vue. Now that there are other options available, I think we can probably drop support.
