### ISSUE TITLE
Allow cli flag for port

### ISSUE THREAD

**Issue by drzax** [abcnews/aunty#16]
It's not that uncommon that I want to use a port other than 8000 to serve something from Aunty. Usually because I'm developing two things at once.

Right now that needs an addition to `package.json`, which is less than ideal because it's not config I want to commit. A command-line flag would be good.

Also, the `package.json` method of changing port doesn't appear to work for webpack projects.

**Comment by nathanhoad** [comment]
I'll fix the Webpack port changing.

**Comment by nathanhoad** [comment]
The `package.json` config (`aunty.serve.port`) is working for Webpack now. I'll have a look at adding a cli flag for it too.

**Comment by colingourlay** [comment]
Fixed in #5.0.0
