### ISSUE TITLE
Fix vulnerabilities

### ISSUE THREAD

**Issue by drzax** [abcnews/aunty#52]
This now has a decent collection of vulnerabilities. We should fix 'em.

**Comment by colingourlay** [comment]
Good call. I'll get them in there before the next release.

**Comment by colingourlay** [comment]
A bunch of dependency updates went out in https://github.com/abcnews/aunty/tree/7.9.0

**Comment by colingourlay** [comment]
We finally managed to get a version of `node-sass` in that doesn't have vulnerable dependencies!
