### ISSUE TITLE
Implement source maps for javascript in debug mode

### ISSUE THREAD

**Issue by drzax** [abcnews/aunty#6]

**Comment by drzax** [comment]
This might be a helpful starting point: https://github.com/gulpjs/gulp/blob/master/docs/recipes/browserify-uglify-sourcemap.md

Any thoughts on this @colingourlay? I'm finding it very frustrating that I can't identify the exact point in source code whenever a build breaks.

**Comment by nathanhoad** [comment]
This is kind related to #9 (Sourcemaps are enabled for Webpack JS)

**Comment by drzax** [comment]
I think this is done. Closing.
