### ISSUE TITLE
Production __webpack_public_path__ defaults to "/"

### ISSUE THREAD

**Issue by phocks** [abcnews/aunty#74]
This looks like it can probably be changed with a webpack argument

`const publicURL = argv.target ? config.deploy[argv.target].publicURL : '/';`

...but I think it might be handy to set this to the Public URL specified when you deploy/release the project?

`Public URL: http://www.abc.net.au/res/sites/news-projects/howlifehaschanged/master/`

This is mostly so that resources linked to with the loader like const `something = require("large.gif")` link to the correct file in the deployed dist directory instead of `src="/large-a1ca79f8f0850cd2e6a2a4329a385d8e.gif"`.

Not sure if this is possible, but raising an issue so I remember to ask @colingourlay about it when he gets back.

Cheers

**Comment by phocks** [comment]
Note: I figured out how to do this manually. Pop this in your webpack config:

```
output: {
      publicPath: "http://www.abc.net.au/res/sites/news-projects/howlifehaschanged/master/"
    }
```

Seems to work as expected. Also doesn't seem to affect the path in development mode server.

**Comment by nathanhoad** [comment]
If you run `nt build` with `--target=contentftp` it automatically adds the full path as a prefix to assets.

We can probably have a look at making this default behaviour for `build` with the option of an override.
