### ISSUE TITLE
Would removing the newsdev3 details cause any problems?

### ISSUE THREAD

**Issue by blakebutcher** [abcnews/aunty#78]
https://github.com/abcnews/aunty/blob/dc0b58847ef25582744df591e501e41e871cea47/src/config/constants.js#L28

**Comment by colingourlay** [comment]
There are a couple of apps using aunty that deploy to newsdev3 (like the quiz builder), but the stuff in aunty itself are just defaults that can be added to their project configs. Not that any of that'll matter when newsdev3 isn't a thing any more.

**Comment by colingourlay** [comment]
They're gone now ;)
