### ISSUE TITLE
Getting async/await working without babel-pollyfill

### ISSUE THREAD

**Issue by phocks** [abcnews/aunty#82]
Previously I've used 

`npm install @babel/polyfill`

and

`require("@babel/polyfill");`

To get async/await working in Aunty projects which throws a `ReferenceError: regeneratorRuntime is not defined` error by default when you try to async a function.

The problem is that this library seems pretty big like 100k or so I think and that adds to the bundle size I believe.

I am seeing that there might be a way to support async/await in the babel transpilation so we don't need to require the pollyfill????

See here: https://medium.com/@binyamin/enabling-async-await-and-generator-functions-in-babel-node-and-express-71e941b183e2

I have tried a few things in the `babel` section of an `aunty.config.js` though without any luck, so I'm just wondering if anyone here like @colingourlay or @nathanhoad or @drzax might know so we can start moving further into es6-7 land :)

**Comment by phocks** [comment]
OK I solved this I think:

1. `npm install regenerator`
2. in your code `import "regenerator-runtime/runtime.js"` or require

Only 7.1k!!!

<img width="516" alt="index_js_ _regl-test" src="https://user-images.githubusercontent.com/437566/50135857-68c2ba00-02e1-11e9-9beb-2d6f148d66d8.png">

**Comment by phocks** [comment]
IE11 may require this https://www.npmjs.com/package/promise-polyfill although Colin reckons Phase 1 desktop articles get Promise Polyfill anyway.

**Comment by nathanhoad** [comment]
I'm hesitant to include a library in all projects that is only used as needed. I did, however, add some notes to the README about how to get `async`/`await` working in projects based on your suggestion of `regenerator-runtime`.

**Comment by phocks** [comment]
Good thinking
