### ISSUE TITLE
Should we update React templates to use function components?

### ISSUE THREAD

**Issue by phocks** [abcnews/aunty#91]
Now that React has released Hooks? Or we could have it as a separate option?

I've been updating new components to look something like this.

```javascript
import React from "react";
import styles from "./styles.scss";

const HeatMap = props => {
  return (
    <div className={styles.root}>
      Find me in <strong>src/components/HeatMap/index.js</strong>
    </div>
  );
};

export default HeatMap;
```

**Comment by nathanhoad** [comment]
I'd be hesitant to add too many options for generating stuff. If everyone is happy with hooks then we can default to using them for the templates.
