### ISSUE TITLE
Calling aunty with no args hangs

### ISSUE THREAD

**Issue by drzax** [abcnews/aunty#93]
`aunty` without args hangs. It would be nice to alias it to `aunty -h`

**Comment by phocks** [comment]
that seems to be the behaviour for me on aunty v10.4.0

prints the help screen with no args

**Comment by drzax** [comment]
Interesting. I'm just getting no output and process stays running. Also 10.4.0.

**Comment by nathanhoad** [comment]
We can't seem to reproduce this. Feel free to reopen if you come across it again.

**Comment by drzax** [comment]
This is still happening for me on v10.5.1 so I'm going to re-open, but I haven't had time to investigate today. Interestingly, it's also now hanging on `aunty -h`, so may not be the same problem.

**Comment by phocks** [comment]
Still prints the help for me with no args and with -h

aunty v10.5.1

**Comment by drzax** [comment]
Can't replicate on new machine. Seems this was environment specific. Closing.
